name: Build and Release zstd (musl static)

on:
  push:
    tags:
      - 'v*'   # 以 v 开头的 Tag 触发
  workflow_dispatch:  # 手动触发
    inputs:
      version:
        description: 'zstd version (e.g. v1.5.7)'
        required: false
        default: 'v1.5.7'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install musl tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools build-essential wget

      - name: Determine version and download source
        id: download
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          VERSION_NO_V=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_NO_V=$VERSION_NO_V" >> $GITHUB_ENV

          echo "Downloading zstd version $VERSION_NO_V ..."
          wget https://github.com/facebook/zstd/releases/download/$VERSION/zstd-$VERSION_NO_V.tar.gz
          tar -xzf zstd-$VERSION_NO_V.tar.gz

      - name: Build static binary with musl
        run: |
          cd zstd-$VERSION_NO_V
          CC=musl-gcc make clean
          CC=musl-gcc make \
            CFLAGS="-O3 -static -flto" \
            LDFLAGS="-static -flto" \
            programs-only
          ls -lh programs/zstd

      - name: Upload static binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: zstd-$VERSION_NO_V/programs/zstd
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
