name: Build and Release zstd (musl static)

on:
  push:
    tags:
      - 'v*'   # 以 v 开头的 Tag 触发
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install musl tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools build-essential wget

      - name: Download zstd source
        id: download
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # 手动触发时用输入的版本号，默认1.5.7
            VERSION="${{ github.event.inputs.version || 'v1.5.7' }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          wget https://github.com/facebook/zstd/releases/download/$VERSION/zstd-${VERSION#v}.tar.gz
          tar -xzf zstd-${VERSION#v}.tar.gz

      - name: Build static binary with musl
        run: |
          cd zstd-${{ env.VERSION#v }}
          CC=musl-gcc make clean
          CC=musl-gcc make \
            CFLAGS="-O3 -static -flto" \
            LDFLAGS="-static -flto" \
            programs-only
          ls -lh programs/zstd

      - name: Upload static binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: zstd-${{ env.VERSION#v }}/programs/zstd
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

